### ISSUE TITLE
Test Case 1

### ISSUE THREAD

**Issue by andrewjgardner** [andrewjgardner/ReservationSystem#115]
### Part 1
Based on Research:

- [ ] Test context and scope
- [ ] Test standard and methodology
- [ ] Test tools and types
- [ ] Test design techniques

Design Test cases using:

- [ ] static test design technique (one of)
- [ ] dynamic test design technique (one of)
- [ ] appropriate test input data determined from the requirements
- [ ] appropriate formatting including test case number, description, preconditions, steps, expected result, and tool name (if applicable).

### Part 2

- [ ] Test Environment
- [ ] Automated Testing tool (If applicable)
- [ ] Research documents regarding test env and/or Automated testing tool

Testing Steps 

- [ ] Test Environment (Screenshots)
- [ ] Test Description 
- [ ] Test Preconditions (Including input data)
- [ ] Testing tool used
- [ ] Test Result (Expected, Actual, Outcome/Recommendation)

### Part 3
Evaluate and fix

- [ ] Details of bug
- [ ] Debugging steps to track the defect
- [ ] Details of fixes implemented
- [ ] Test results after debugging
